/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PD2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ngehe
 */
public class Start_Menu extends javax.swing.JFrame {

    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    static int[] pertanyaan = {8, 4, 12, 2, 6, 1, 3, 5, 7, 10, 14, 9, 11, 13, 15};
    BinaryTree soal = new BinaryTree();

    /**
     * Creates new form Start_Menu
     */
    public Start_Menu() throws SQLException {
        initComponents();
        koneksi DB = new koneksi();
        DB.connect();
        con = DB.con;
        stat = DB.stm;
        this.setSize(965, 606);
        for (int i = 0; i < pertanyaan.length; i++) {
            soal.push(new Node(pertanyaan[i]));
        }
        soal.print();
        soal.current = soal.root;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOGIN = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        masuk = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DAFTAR = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        uname = new javax.swing.JTextField();
        daftar = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kategori_game = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        game_button = new javax.swing.JButton();
        anime_button = new javax.swing.JButton();
        kpop_button = new javax.swing.JButton();
        drama_button = new javax.swing.JButton();
        kartun_button = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        NEW_GAME = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Game = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        game_text = new javax.swing.JTextArea();
        optionA = new javax.swing.JRadioButton();
        optionB = new javax.swing.JRadioButton();
        kirim_game = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Anime = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        option_yes = new javax.swing.JRadioButton();
        option_no = new javax.swing.JRadioButton();
        anime_kirim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        soal_column = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        kpop = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        option_yes1 = new javax.swing.JRadioButton();
        option_no1 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        soal_column1 = new javax.swing.JTextArea();
        Kpop_kirim = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        kdrama = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        soal_column2 = new javax.swing.JTextArea();
        option_no2 = new javax.swing.JRadioButton();
        option_yes2 = new javax.swing.JRadioButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        kartun = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        soal_column3 = new javax.swing.JTextArea();
        option_yes3 = new javax.swing.JRadioButton();
        option_no3 = new javax.swing.JRadioButton();
        jButton17 = new javax.swing.JButton();
        kartun_kirim = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        radio = new javax.swing.ButtonGroup();
        anime_radio = new javax.swing.ButtonGroup();
        kesimpulan = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ksmpln = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        signin = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        highscore = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        LOGIN.setIconImage(null);

        jPanel2.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("USERNAME");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 100, 92, 30);

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel2.add(user);
        user.setBounds(150, 100, 190, 30);

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel2.add(pass);
        pass.setBounds(150, 140, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("PASSWORD");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 140, 95, 30);

        masuk.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        masuk.setText("Masuk");
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });
        jPanel2.add(masuk);
        masuk.setBounds(250, 200, 90, 29);

        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(150, 200, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PD2/image/login.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout LOGINLayout = new javax.swing.GroupLayout(LOGIN.getContentPane());
        LOGIN.getContentPane().setLayout(LOGINLayout);
        LOGINLayout.setHorizontalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LOGINLayout.setVerticalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DAFTAR.setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel8.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel8.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("E-mail");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(70, 120, 52, 30);

        cancel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cancel.setText("Back");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel8.add(cancel);
        cancel.setBounds(130, 240, 90, 29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Username");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(40, 160, 82, 30);

        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });
        jPanel8.add(pwd);
        pwd.setBounds(130, 200, 230, 30);
        jPanel8.add(uname);
        uname.setBounds(130, 160, 230, 30);

        daftar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        daftar.setText("Daftar");
        daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarActionPerformed(evt);
            }
        });
        jPanel8.add(daftar);
        daftar.setBounds(270, 240, 90, 29);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel8.add(nama);
        nama.setBounds(130, 80, 230, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Password");
        jPanel8.add(jLabel10);
        jLabel10.setBounds(40, 200, 78, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Nama");
        jPanel8.add(jLabel6);
        jLabel6.setBounds(70, 80, 47, 30);
        jPanel8.add(email);
        email.setBounds(130, 120, 230, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PD2/image/signup.jpg"))); // NOI18N
        jPanel8.add(jLabel7);
        jLabel7.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout DAFTARLayout = new javax.swing.GroupLayout(DAFTAR.getContentPane());
        DAFTAR.getContentPane().setLayout(DAFTARLayout);
        DAFTARLayout.setHorizontalGroup(
            DAFTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DAFTARLayout.setVerticalGroup(
            DAFTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        kategori_game.setMinimumSize(new java.awt.Dimension(600, 600));

        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel8.setText("KATEGORI");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(420, 160, 190, 60);

        game_button.setText("GAME");
        game_button.setActionCommand("Game");
        game_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(game_button);
        game_button.setBounds(420, 280, 180, 40);

        anime_button.setText("ANIME");
        anime_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anime_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(anime_button);
        anime_button.setBounds(420, 230, 180, 40);

        kpop_button.setText("KPOP");
        kpop_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kpop_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(kpop_button);
        kpop_button.setBounds(420, 330, 180, 40);

        drama_button.setText("KDRAMA");
        drama_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drama_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(drama_button);
        drama_button.setBounds(420, 380, 180, 40);

        kartun_button.setText("KARTUN");
        kartun_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartun_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(kartun_button);
        kartun_button.setBounds(420, 430, 180, 40);

        jButton10.setText("KEMBALI");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);
        jButton10.setBounds(20, 530, 110, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PD2/image/mainmenu.jpg"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 0, 950, 570);

        javax.swing.GroupLayout kategori_gameLayout = new javax.swing.GroupLayout(kategori_game.getContentPane());
        kategori_game.getContentPane().setLayout(kategori_gameLayout);
        kategori_gameLayout.setHorizontalGroup(
            kategori_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kategori_gameLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kategori_gameLayout.setVerticalGroup(
            kategori_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kategori_gameLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        NEW_GAME.setIconImage(null);

        jPanel5.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel5.setLayout(null);

        jButton6.setText("New Game");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(140, 100, 130, 60);

        jButton9.setText("Logout");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9);
        jButton9.setBounds(140, 180, 130, 60);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PD2/image/newgame.jpg"))); // NOI18N
        jPanel5.add(jLabel15);
        jLabel15.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout NEW_GAMELayout = new javax.swing.GroupLayout(NEW_GAME.getContentPane());
        NEW_GAME.getContentPane().setLayout(NEW_GAMELayout);
        NEW_GAMELayout.setHorizontalGroup(
            NEW_GAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NEW_GAMELayout.setVerticalGroup(
            NEW_GAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Game.setMinimumSize(new java.awt.Dimension(800, 496));

        jPanel7.setLayout(null);

        jButton12.setText("LOGOUT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12);
        jButton12.setBounds(20, 520, 130, 50);

        game_text.setColumns(20);
        game_text.setLineWrap(true);
        game_text.setRows(5);
        jScrollPane2.setViewportView(game_text);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(110, 200, 730, 110);

        radio.add(optionA);
        optionA.setForeground(java.awt.Color.white);
        optionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionAActionPerformed(evt);
            }
        });
        jPanel7.add(optionA);
        optionA.setBounds(110, 360, 340, 21);

        radio.add(optionB);
        optionB.setForeground(java.awt.Color.white);
        jPanel7.add(optionB);
        optionB.setBounds(470, 360, 360, 21);

        kirim_game.setText("Kirim");
        kirim_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirim_gameActionPerformed(evt);
            }
        });
        jPanel7.add(kirim_game);
        kirim_game.setBounds(410, 410, 120, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PD2/image/mainmenu.jpg"))); // NOI18N
        jPanel7.add(jLabel13);
        jLabel13.setBounds(0, 0, 950, 576);

        javax.swing.GroupLayout GameLayout = new javax.swing.GroupLayout(Game.getContentPane());
        Game.getContentPane().setLayout(GameLayout);
        GameLayout.setHorizontalGroup(
            GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GameLayout.setVerticalGroup(
            GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Anime.setMinimumSize(new java.awt.Dimension(800, 496));

        jPanel9.setLayout(null);

        jButton13.setText("EXIT");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton13);
        jButton13.setBounds(40, 520, 110, 40);

        anime_radio.add(option_yes);
        option_yes.setText("jRadioButton1");
        jPanel9.add(option_yes);
        option_yes.setBounds(90, 350, 390, 23);

        anime_radio.add(option_no);
        option_no.setText("jRadioButton2");
        jPanel9.add(option_no);
        option_no.setBounds(490, 350, 360, 23);

        anime_kirim.setText("Kirim");
        anime_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anime_kirimActionPerformed(evt);
            }
        });
        jPanel9.add(anime_kirim);
        anime_kirim.setBounds(420, 410, 120, 50);

        soal_column.setColumns(20);
        soal_column.setLineWrap(true);
        soal_column.setRows(5);
        jScrollPane1.setViewportView(soal_column);

        jPanel9.add(jScrollPane1);
        jScrollPane1.setBounds(90, 210, 760, 96);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PD2/image/mainmenu.jpg"))); // NOI18N
        jPanel9.add(jLabel14);
        jLabel14.setBounds(0, 0, 950, 576);

        javax.swing.GroupLayout AnimeLayout = new javax.swing.GroupLayout(Anime.getContentPane());
        Anime.getContentPane().setLayout(AnimeLayout);
        AnimeLayout.setHorizontalGroup(
            AnimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnimeLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AnimeLayout.setVerticalGroup(
            AnimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnimeLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        kpop.setMinimumSize(new java.awt.Dimension(800, 496));

        jPanel10.setLayout(null);

        jButton14.setText("EXIT");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton14);
        jButton14.setBounds(20, 540, 100, 23);

        anime_radio.add(option_yes1);
        option_yes1.setText("jRadioButton1");
        jPanel10.add(option_yes1);
        option_yes1.setBounds(90, 350, 340, 23);

        anime_radio.add(option_no1);
        option_no1.setText("jRadioButton2");
        jPanel10.add(option_no1);
        option_no1.setBounds(490, 350, 360, 23);

        soal_column1.setColumns(20);
        soal_column1.setLineWrap(true);
        soal_column1.setRows(5);
        jScrollPane3.setViewportView(soal_column1);

        jPanel10.add(jScrollPane3);
        jScrollPane3.setBounds(90, 210, 760, 96);

        Kpop_kirim.setText("Kirim");
        Kpop_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kpop_kirimActionPerformed(evt);
            }
        });
        jPanel10.add(Kpop_kirim);
        Kpop_kirim.setBounds(430, 400, 120, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PD2/image/mainmenu.jpg"))); // NOI18N
        jPanel10.add(jLabel16);
        jLabel16.setBounds(0, 0, 950, 576);

        javax.swing.GroupLayout kpopLayout = new javax.swing.GroupLayout(kpop.getContentPane());
        kpop.getContentPane().setLayout(kpopLayout);
        kpopLayout.setHorizontalGroup(
            kpopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kpopLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kpopLayout.setVerticalGroup(
            kpopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kpopLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        kdrama.setMinimumSize(new java.awt.Dimension(800, 496));

        jPanel11.setLayout(null);

        soal_column2.setColumns(20);
        soal_column2.setLineWrap(true);
        soal_column2.setRows(5);
        jScrollPane4.setViewportView(soal_column2);

        jPanel11.add(jScrollPane4);
        jScrollPane4.setBounds(90, 210, 760, 96);

        anime_radio.add(option_no2);
        option_no2.setText("jRadioButton2");
        jPanel11.add(option_no2);
        option_no2.setBounds(490, 350, 360, 23);

        anime_radio.add(option_yes2);
        option_yes2.setText("jRadioButton1");
        jPanel11.add(option_yes2);
        option_yes2.setBounds(90, 350, 340, 23);

        jButton15.setText("LOGOUT");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton15);
        jButton15.setBounds(20, 540, 100, 23);

        jButton16.setText("Kirim");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton16);
        jButton16.setBounds(420, 410, 120, 50);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PD2/image/mainmenu.jpg"))); // NOI18N
        jPanel11.add(jLabel17);
        jLabel17.setBounds(0, 0, 950, 576);

        javax.swing.GroupLayout kdramaLayout = new javax.swing.GroupLayout(kdrama.getContentPane());
        kdrama.getContentPane().setLayout(kdramaLayout);
        kdramaLayout.setHorizontalGroup(
            kdramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kdramaLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kdramaLayout.setVerticalGroup(
            kdramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kdramaLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        kartun.setMinimumSize(new java.awt.Dimension(800, 496));

        jPanel12.setLayout(null);

        soal_column3.setColumns(20);
        soal_column3.setLineWrap(true);
        soal_column3.setRows(5);
        jScrollPane5.setViewportView(soal_column3);

        jPanel12.add(jScrollPane5);
        jScrollPane5.setBounds(90, 210, 760, 96);

        anime_radio.add(option_yes3);
        option_yes3.setText("jRadioButton1");
        jPanel12.add(option_yes3);
        option_yes3.setBounds(90, 350, 340, 23);

        anime_radio.add(option_no3);
        option_no3.setText("jRadioButton2");
        jPanel12.add(option_no3);
        option_no3.setBounds(490, 350, 360, 23);

        jButton17.setText("LOGOUT");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton17);
        jButton17.setBounds(20, 540, 100, 23);

        kartun_kirim.setText("Kirim");
        kartun_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartun_kirimActionPerformed(evt);
            }
        });
        jPanel12.add(kartun_kirim);
        kartun_kirim.setBounds(420, 410, 120, 50);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PD2/image/mainmenu.jpg"))); // NOI18N
        jPanel12.add(jLabel18);
        jLabel18.setBounds(0, 0, 950, 576);

        javax.swing.GroupLayout kartunLayout = new javax.swing.GroupLayout(kartun.getContentPane());
        kartun.getContentPane().setLayout(kartunLayout);
        kartunLayout.setHorizontalGroup(
            kartunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartunLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kartunLayout.setVerticalGroup(
            kartunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartunLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setLayout(null);

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(490, 470, 120, 40);

        jButton2.setText("NEW GAME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(340, 470, 120, 40);

        ksmpln.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ksmpln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(ksmpln);
        ksmpln.setBounds(50, 220, 840, 210);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PD2/image/mainmenu.jpg"))); // NOI18N
        jPanel4.add(jLabel19);
        jLabel19.setBounds(0, 0, 950, 576);

        javax.swing.GroupLayout kesimpulanLayout = new javax.swing.GroupLayout(kesimpulan.getContentPane());
        kesimpulan.getContentPane().setLayout(kesimpulanLayout);
        kesimpulanLayout.setHorizontalGroup(
            kesimpulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kesimpulanLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kesimpulanLayout.setVerticalGroup(
            kesimpulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kesimpulanLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 576));

        jPanel1.setLayout(null);

        signin.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        signin.setText("LOGIN");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        jPanel1.add(signin);
        signin.setBounds(395, 178, 157, 77);

        signup.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        signup.setText("SIGN UP");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        jPanel1.add(signup);
        signup.setBounds(395, 261, 157, 67);

        exit.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(395, 409, 157, 78);

        highscore.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        highscore.setText("BANTUAN");
        highscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoreActionPerformed(evt);
            }
        });
        jPanel1.add(highscore);
        highscore.setBounds(395, 334, 157, 69);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PD2/image/mainmenu.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 950, 576);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        LOGIN.setVisible(true);
        LOGIN.setSize(415, 340);
        this.dispose();
    }//GEN-LAST:event_signinActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        DAFTAR.setVisible(true);
        DAFTAR.setSize(415, 340);
        this.dispose();
    }//GEN-LAST:event_signupActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void highscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highscoreActionPerformed

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        try {
            sql = "SELECT username,password FROM login WHERE username='" + user.getText() + "' AND password='" + pass.getText() + "'";
            rs = stat.executeQuery(sql);
            if (rs.next()) {
                if (user.getText().equals(rs.getString("username")) && pass.getText().equals(rs.getString("password"))) {
                    JOptionPane.showMessageDialog(null, "berhasil login");
                    user.setText("");
                    pass.setText("");
                    NEW_GAME.setVisible(true);
                    NEW_GAME.setSize(415, 340);
                    LOGIN.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "username atau password salah");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_masukActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(true);
        user.setText("");
        pass.setText("");
        LOGIN.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.setVisible(true);
        DAFTAR.dispose();

    }//GEN-LAST:event_cancelActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    private void daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarActionPerformed
        try {
            sql = "insert into login(nama,email, username,password) values ('" + nama.getText() + "','" + email.getText() + "','" + uname.getText() + "','" + pwd.getText() + "')";
            if (nama.getText().equals("") || email.getText().equals("") || uname.getText().equals("") || pwd.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "KOLOM TIDAK BOLEH KOSONG");
            } else {
                stat.execute(sql);
                JOptionPane.showMessageDialog(null, "DAFTAR SUKSES");
                nama.setText("");
                email.setText("");
                uname.setText("");
                pwd.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_daftarActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void game_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game_buttonActionPerformed
//        System.out.println(soal.getRoot().data);
//        try {
//            sql = "SELECT * from soal where id_soal = '" + "GM0" + String.valueOf(soal.root.data) + "'";
//            rs = stat.executeQuery(sql);
//            if (rs.next()) {
//                game_text.setText(rs.getString("soal"));
//                optionA.setText(rs.getString("opsi1"));
//                optionB.setText(rs.getString("opsi2"));
//                Game.setVisible(true);
//                Game.setSize(965, 606);
//                kategori_game.dispose();
//
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_game_buttonActionPerformed

    private void drama_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drama_buttonActionPerformed
//        System.out.println(soal.getRoot().data);
//        try {
//            sql = "SELECT * from soal where id_soal = '" + "KD0" + String.valueOf(soal.root.data) + "'";
//            rs = stat.executeQuery(sql);
//            if (rs.next()) {
//                soal_column2.setText(rs.getString("soal"));
//                option_yes2.setText(rs.getString("opsi1"));
//                option_no2.setText(rs.getString("opsi2"));
//                kdrama.setVisible(true);
//                kdrama.setSize(965, 606);
//                kategori_game.dispose();
//
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_drama_buttonActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        NEW_GAME.setVisible(true);
        kategori_game.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void kpop_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kpop_buttonActionPerformed
//        System.out.println(soal.getRoot().data);
//        try {
//            sql = "SELECT * from soal where id_soal = '" + "KP0" + String.valueOf(soal.root.data) + "'";
//            rs = stat.executeQuery(sql);
//            if (rs.next()) {
//                soal_column1.setText(rs.getString("soal"));
//                option_yes1.setText(rs.getString("opsi1"));
//                option_no1.setText(rs.getString("opsi2"));
//                kpop.setVisible(true);
//                kpop.setSize(965, 606);
//                kategori_game.dispose();
//
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_kpop_buttonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        kategori_game.setVisible(true);
        kategori_game.setSize(965, 606);
        NEW_GAME.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.setVisible(true);
        NEW_GAME.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void anime_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anime_buttonActionPerformed
        System.out.println(soal.getRoot().data);
        try {
            sql = "SELECT * from soal where id_soal = '" + "AN0" + String.valueOf(soal.root.data) + "'";
            rs = stat.executeQuery(sql);
            if (rs.next()) {
                soal_column.setText(rs.getString("soal"));
                option_yes.setText(rs.getString("opsi1"));
                option_no.setText(rs.getString("opsi2"));
                Anime.setVisible(true);
                Anime.setSize(965, 606);
                kategori_game.dispose();

            }
        } catch (SQLException ex) {
            Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_anime_buttonActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        kategori_game.setVisible(true);
        soal.current = soal.root;
        user.setText("");
        pass.setText("");
        Game.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        kategori_game.setVisible(true);
        soal.current = soal.root;
        user.setText("");
        pass.setText("");
        Anime.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        kategori_game.setVisible(true);
        soal.current = soal.root;
        user.setText("");
        pass.setText("");
        kpop.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        kategori_game.setVisible(true);
        soal.current = soal.root;
        user.setText("");
        pass.setText("");
        kdrama.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        kategori_game.setVisible(true);
        soal.current = soal.root;
        user.setText("");
        pass.setText("");
        kartun.dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void kartun_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartun_buttonActionPerformed
//        System.out.println(soal.getRoot().data);
//        try {
//            sql = "SELECT * from soal where id_soal = '" + "KT0" + String.valueOf(soal.root.data) + "'";
//            rs = stat.executeQuery(sql);
//            if (rs.next()) {
//                soal_column3.setText(rs.getString("soal"));
//                option_yes3.setText(rs.getString("opsi1"));
//                option_no3.setText(rs.getString("opsi2"));
//                kartun.setVisible(true);
//                kartun.setSize(965, 606);
//                kategori_game.dispose();
//
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_kartun_buttonActionPerformed

    private void anime_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anime_kirimActionPerformed
        while (soal.current != null) {
            if (option_yes.isSelected()) {
                soal.current = soal.current.yes;
                System.out.println(soal.getCurrentData());
                try {
                    sql = "SELECT * from soal where id_soal = '" + "AN0" + String.valueOf(soal.getCurrentData()) + "'";
                    rs = stat.executeQuery(sql);
                    if (rs.next()) {
                        soal_column.setText(rs.getString("soal"));
                        option_yes.setText(rs.getString("opsi1"));
                        option_no.setText(rs.getString("opsi2"));
                        Anime.setVisible(true);
                        Anime.setSize(965, 606);
                        this.dispose();

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (option_no.isSelected()) {
                soal.current = soal.current.no;
                System.out.println(soal.getCurrentData());
                try {
                    sql = "SELECT * from soal where id_soal = '" + "AN0" + String.valueOf(soal.getCurrentData()) + "'";
                    rs = stat.executeQuery(sql);
                    if (rs.next()) {
                        soal_column.setText(rs.getString("soal"));
                        option_yes.setText(rs.getString("opsi1"));
                        option_no.setText(rs.getString("opsi2"));
                        Anime.setVisible(true);
                        Anime.setSize(965, 606);
                        this.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (soal.current.has_no_child()) {
                try {
                    sql = "SELECT soal from soal where id_soal = '" + "AN0" + String.valueOf(soal.getCurrentData()) + "'";
                    rs = stat.executeQuery(sql);
                    if (rs.next()) {
                        kesimpulan.setVisible(true);
                        kesimpulan.setSize(965, 606);
                        Anime.dispose();
                        ksmpln.setText(rs.getString("soal"));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            }
            break;
        }
    }//GEN-LAST:event_anime_kirimActionPerformed

    private void kirim_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirim_gameActionPerformed
//       while (soal.current != null) {
//            if (optionA.isSelected()) {
//                soal.current = soal.current.yes;
//                System.out.println(soal.getCurrentData());
//                try {
//                    sql = "SELECT * from soal where id_soal = '" + "GM0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        game_text.setText(rs.getString("soal"));
//                        optionA.setText(rs.getString("opsi1"));
//                        optionB.setText(rs.getString("opsi2"));
//                        Game.setVisible(true);
//                        Game.setSize(965, 606);
//                        this.dispose();
//
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            if (optionB.isSelected()) {
//                soal.current = soal.current.no;
//                System.out.println(soal.getCurrentData());
//                try {
//                    sql = "SELECT * from soal where id_soal = '" + "KP0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        game_text.setText(rs.getString("soal"));
//                        optionA.setText(rs.getString("opsi1"));
//                        optionB.setText(rs.getString("opsi2"));
//                        Game.setVisible(true);
//                        Game.setSize(965, 606);
//                        this.dispose();
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            if (soal.current.has_no_child()) {
//                try {
//                    sql = "SELECT soal from soal where id_soal = '" + "KP0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        kesimpulan.setVisible(true);
//                        kesimpulan.setSize(965, 606);
//                        Game.dispose();
//                        ksmpln.setText(rs.getString("soal"));
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                break;
//            }
//            break;
//        }
    }//GEN-LAST:event_kirim_gameActionPerformed

    private void Kpop_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kpop_kirimActionPerformed
//       while (soal.current != null) {
//            if (option_yes1.isSelected()) {
//                soal.current = soal.current.yes;
//                System.out.println(soal.getCurrentData());
//                try {
//                    sql = "SELECT * from soal where id_soal = '" + "KP0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        soal_column1.setText(rs.getString("soal"));
//                        option_yes1.setText(rs.getString("opsi1"));
//                        option_no1.setText(rs.getString("opsi2"));
//                        kpop.setVisible(true);
//                        kpop.setSize(965, 606);
//                        this.dispose();
//
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            if (option_no1.isSelected()) {
//                soal.current = soal.current.no;
//                System.out.println(soal.getCurrentData());
//                try {
//                    sql = "SELECT * from soal where id_soal = '" + "KP0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        soal_column1.setText(rs.getString("soal"));
//                        option_yes1.setText(rs.getString("opsi1"));
//                        option_no1.setText(rs.getString("opsi2"));
//                        kpop.setVisible(true);
//                        kpop.setSize(965, 606);
//                        this.dispose();
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            if (soal.current.has_no_child()) {
//                try {
//                    sql = "SELECT soal from soal where id_soal = '" + "KP0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        kesimpulan.setVisible(true);
//                        kesimpulan.setSize(965, 606);
//                        kpop.dispose();
//                        ksmpln.setText(rs.getString("soal"));
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                break;
//            }
//            break;
//        }
    }//GEN-LAST:event_Kpop_kirimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        soal.current = soal.root;
        kategori_game.setVisible(true);
        kategori_game.setSize(965, 606);
        kesimpulan.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void optionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionAActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        //       while (soal.current != null) {
//            if (option_yes2.isSelected()) {
//                soal.current = soal.current.yes;
//                System.out.println(soal.getCurrentData());
//                try {
//                    sql = "SELECT * from soal where id_soal = '" + "KD0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        soal_column2.setText(rs.getString("soal"));
//                        option_yes2.setText(rs.getString("opsi1"));
//                        option_no2.setText(rs.getString("opsi2"));
//                        kdrama.setVisible(true);
//                        kdrama.setSize(965, 606);
//                        this.dispose();
//
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            if (option_no2.isSelected()) {
//                soal.current = soal.current.no;
//                System.out.println(soal.getCurrentData());
//                try {
//                    sql = "SELECT * from soal where id_soal = '" + "KD0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        soal_column2.setText(rs.getString("soal"));
//                        option_yes2.setText(rs.getString("opsi1"));
//                        option_no2.setText(rs.getString("opsi2"));
//                        kdrama.setVisible(true);
//                        kdrama.setSize(965, 606);
//                        this.dispose();
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            if (soal.current.has_no_child()) {
//                try {
//                    sql = "SELECT soal from soal where id_soal = '" + "KD0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        kesimpulan.setVisible(true);
//                        kesimpulan.setSize(965, 606);
//                        kdrama.dispose();
//                        ksmpln.setText(rs.getString("soal"));
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                break;
//            }
//            break;
//        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void kartun_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartun_kirimActionPerformed
//        while (soal.current != null) {
//            if (option_yes3.isSelected()) {
//                soal.current = soal.current.yes;
//                System.out.println(soal.getCurrentData());
//                try {
//                    sql = "SELECT * from soal where id_soal = '" + "KT0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        soal_column3.setText(rs.getString("soal"));
//                        option_yes3.setText(rs.getString("opsi1"));
//                        option_no3.setText(rs.getString("opsi2"));
//                        kartun.setVisible(true);
//                        kartun.setSize(965, 606);
//                        this.dispose();
//
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            if (option_no3.isSelected()) {
//                soal.current = soal.current.no;
//                System.out.println(soal.getCurrentData());
//                try {
//                    sql = "SELECT * from soal where id_soal = '" + "KT0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        soal_column3.setText(rs.getString("soal"));
//                        option_yes3.setText(rs.getString("opsi1"));
//                        option_no3.setText(rs.getString("opsi2"));
//                        kartun.setVisible(true);
//                        kartun.setSize(965, 606);
//                        this.dispose();
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            if (soal.current.has_no_child()) {
//                try {
//                    sql = "SELECT soal from soal where id_soal = '" + "KT0" + String.valueOf(soal.getCurrentData()) + "'";
//                    rs = stat.executeQuery(sql);
//                    if (rs.next()) {
//                        kesimpulan.setVisible(true);
//                        kesimpulan.setSize(965, 606);
//                        kartun.dispose();
//                        ksmpln.setText(rs.getString("soal"));
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                break;
//            }
//            break;
//        }
    }//GEN-LAST:event_kartun_kirimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Start_Menu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Start_Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Anime;
    private javax.swing.JDialog DAFTAR;
    private javax.swing.JDialog Game;
    private javax.swing.JButton Kpop_kirim;
    private javax.swing.JDialog LOGIN;
    private javax.swing.JDialog NEW_GAME;
    private javax.swing.JButton anime_button;
    private javax.swing.JButton anime_kirim;
    private javax.swing.ButtonGroup anime_radio;
    private javax.swing.JButton back;
    private javax.swing.JButton cancel;
    private javax.swing.JButton daftar;
    private javax.swing.JButton drama_button;
    private javax.swing.JTextField email;
    private javax.swing.JButton exit;
    private javax.swing.JButton game_button;
    private javax.swing.JTextArea game_text;
    private javax.swing.JButton highscore;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDialog kartun;
    private javax.swing.JButton kartun_button;
    private javax.swing.JButton kartun_kirim;
    private javax.swing.JDialog kategori_game;
    private javax.swing.JDialog kdrama;
    private javax.swing.JDialog kesimpulan;
    private javax.swing.JButton kirim_game;
    private javax.swing.JDialog kpop;
    private javax.swing.JButton kpop_button;
    private javax.swing.JLabel ksmpln;
    private javax.swing.JButton masuk;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton optionA;
    private javax.swing.JRadioButton optionB;
    private javax.swing.JRadioButton option_no;
    private javax.swing.JRadioButton option_no1;
    private javax.swing.JRadioButton option_no2;
    private javax.swing.JRadioButton option_no3;
    private javax.swing.JRadioButton option_yes;
    private javax.swing.JRadioButton option_yes1;
    private javax.swing.JRadioButton option_yes2;
    private javax.swing.JRadioButton option_yes3;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pwd;
    private javax.swing.ButtonGroup radio;
    private javax.swing.JButton signin;
    private javax.swing.JButton signup;
    private javax.swing.JTextArea soal_column;
    private javax.swing.JTextArea soal_column1;
    private javax.swing.JTextArea soal_column2;
    private javax.swing.JTextArea soal_column3;
    private javax.swing.JTextField uname;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
